### ISSUE TITLE
作者你好，你这个代码是不是是完整的

### ISSUE THREAD

**Issue by 1998wq** [AI-Zhpp/FTN#1]

**Comment by AI-Zhpp** [comment]
This is not full for the exact reproduction. It is a simply version. We will release the full code for improved results.

**Comment by 1998wq** [comment]
> This is not full for the exact reproduction. It is a simply version. We will release the full code for improved results.
请问完整的什么时候公布呢

**Comment by wulei1595** [comment]
> 对于精确的复制，这还不够完整。这是一个简单的版本。我们将发布完整的代码以改进结果。

什么时候发布完整代码呢

**Comment by zifuwan** [comment]
您好，最新版本的代码将在这周末发布。此外，您可以通过邮箱与我交流疑问：wanzifu2000@gmail.com
@wulei1595

**Comment by DaGuangDaGuang** [comment]
Good paper! Waiting for your complete code in this weekend!

**Comment by zifuwan** [comment]
Hi, we have updated the code and you may proceed with the experiments according to README.md.

**Comment by DaGuangDaGuang** [comment]
Could you please provide the data set after processing? Thank you very much! My email is 2563489133@qq.com

**Comment by Jeff001128** [comment]
@DaGuangDaGuang Of course. I'm uploading the datasets.

**Comment by zifuwan** [comment]
@DaGuangDaGuang Of course. We will upload the datasets later.
