### ISSUE TITLE
picture size

### ISSUE THREAD

**Issue by DaGuangDaGuang** [AI-Zhpp/FTN#2]
Can I experiment with 256 × 256 pictures

**Comment by zifuwan** [comment]
Hi, you may resize the pics to 224 according to the file _data/dataset_swin_sysu.py_.

**Comment by wulei1595** [comment]
> 



> 嗨，您可以根据文件_数据/dataset_swin_sysu.py_将图片大小调整为 224。

The treatment of the dataset in the paper is cropping, and I think direct scaling is unreasonable
