### ISSUE TITLE
您好，关于您代码里面的这个r是什么

### ISSUE THREAD

**Issue by wulei1595** [AI-Zhpp/FTN#4]
![image](https://user-images.githubusercontent.com/92584533/230533004-f4b670da-bef0-4aa0-a5ff-551dbb1de62e.png)

**Comment by wulei1595** [comment]
我运行代码时提示未定义这个r，是没输入完全还是

**Comment by zifuwan** [comment]
您好，很抱歉造成了困扰。
整理代码时多删了两个字母，此处”r“应该是”res“，已经更正，感谢指出。
